### ISSUE TITLE
How do I install the plug-in?

### ISSUE THREAD

**Issue by kimghoon** [ProLoser/CakePHP-CSV#19]
How do I install the plug-in?
cakephp 3 plugins in the plugin was downloaded copy.
And I added the following code to initialize method to fooTable.php.

$ options = array (
             // Refer to php.net fgetcsv for more information
             'length' => 0,
             'delimiter' => ',',
             'enclosure' => '"',
             'escape' => '\\',
             // Generates a Model.field headings row from the csv file
             'headers' => true,
             // If true, String $ content is the data, not a path to the file
             'text' => false,
         );
         $ this-> addBehavior ('CakePHPCSV.Csv', $ options);

Running comes the following error:

CakePHPCSV.CsvBehavior could not be found.

Make sure your plugin CakePHPCSV is in the / var / www / source / plugins / directory and was loaded.

composer not found CakePHP-CSV

**Comment by ProLoser** [comment]
CakePHP-CSV.Csv
