### ISSUE TITLE
Unable to add in Plugin Folder

### ISSUE THREAD

**Issue by gauravtayal2013** [ProLoser/CakePHP-CSV#28]
Missing Plugin
Cake\Core\Exception\MissingPluginException
Documentation API
Error: The application is trying to load a file from the CakePHPCSV plugin. 

Make sure your plugin CakePHPCSV is in the D:\xampp\htdocs\cakephp\plugins\ directory and was loaded.

<?php
Plugin::load('CakePHPCSV');

Loading all plugins: If you wish to load all plugins at once, use the following line in your config\bootstrap.php file

<?php
Plugin::loadAll();

If you want to customize this error message, create src\Template\Error\missing_plugin.ctp

I am getting this issue please tell me how can i add this plugin in my project. Step wise

**Comment by xhs345** [comment]
Here is what works for me:
1. Download the zip of the correct branch (depending on your CakePHP version)
2. Extract everything to: <cakephp_app_folder>\app\Plugin\Csv
3. Make sure your bootstrap.php file has the line Plugin::loadAll(); (or CakePlugin::load('Csv');)

More info here: http://book.cakephp.org/2.0/en/plugins/how-to-install-plugins.html

**Comment by gauravtayal2013** [comment]
its not working for me. I don't know what is the problem can you tell proper steps and folder's name properly

**Comment by xhs345** [comment]
Sorry, can't make it easier than that. Just try some more reading and testing, maybe with different plugins

**Comment by jransom-flint** [comment]
I had the same issue.  Here's the manual installation process:

1) In the cakephp 'plugins' directory, create a folder "CakePHPCSV"
2) Copy the contents of CakePHP-CSV into this folder.  The structure to CsvBehavior.php should be:

/plugins/CakePHPCSV/src/Model/Behavior/CsvBehavior.php

3) in your config/bootstrap.php add the line:  Plugin::load('CakePHPCSV',['autoload' => true]);

From here the instructions were good, and the plugin loads.

**Comment by gauravtayal2013** [comment]
Issue has been resolved thanks jranson-flint. but you have to use "importCsv"  not only import

**Comment by jransom-flint** [comment]
I see what you mean, there does appear to be a typo on the author's instructions with the import routine.  Good catch!

**Comment by ProLoser** [comment]
Sorry about that, can someone submit a PR with a correction? I don't use Cake/PHP anymore
