### ISSUE TITLE
Number of rows to skip

### ISSUE THREAD

**Issue by fr0z3nfyr** [ProLoser/CakePHP-CSV#29]
I think it will be a good enhancement. Consider a situation where a CSV template is used with headers in top few rows (for sake of example, top 1 row) to perform bulk upload on some model. This option will come very handy - I have it in my own work to do CSV import.

Anyways, a simple and effective way of doing it can be something like (there are many possible alternatives):
```
public $defaults = array(
		'length' => 0,
		'delimiter' => ',',
		'enclosure' => '"',
		'escape' => '\\',
		'headers' => true,
		'skiprows' => 1		// number of rows to skip from beginning
	);
```
Note the additional entry `skiprows`.

Then in your `import()`:
```
while ($row = fgetcsv($file, $options['length'], $options['delimiter'], $options['enclosure'])) {
				if($r < $options['skiprows']) {   // added this condition
					$r++; continue;   // don't forget to do r++
				}
				// for each header field
				foreach ($fields as $f => $field) {
					...
				}
				r++;
			}
			...
		}
		...
	}
```

**Comment by ProLoser** [comment]
No. Seems like something you could accomplish by simply splicing the array after importing.
