### ISSUE TITLE
Line endings Macintosh

### ISSUE THREAD

**Issue by designvoid** [ProLoser/CakePHP-CSV#6]
If you are uploading a CSV created on a Mac you may have issues with it not detecting line endings correctly.
I fixed this by adding the following to the initialize method in the component:

ini_set("auto_detect_line_endings", true);

**Comment by davo3** [comment]
I had the same issue, took some time to figure out the solution, I guess would be great to have the option after all. thanks

**Comment by ProLoser** [comment]
https://github.com/ProLoser/CakePHP-CSV/commit/a1dde42ac94a7169477b743122c4caa625476cc4
